#FROM ubuntu:16.04
#
#RUN apt-get update && apt-get -y upgrade
#
#RUN apt-get -y install vim
#
#RUN apt-get install -y curl
#
#RUN apt-get install -y software-properties-common && add-apt-repository ppa:jonathonf/python-3.6 && update
#
#RUN apt-get install -y build-essential python3.6 python3.6-dev python3-pip

FROM ubuntu:16.04

RUN apt-get update && \
  apt-get install -y software-properties-common && \
  add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update

RUN apt-get install -y build-essential python3.6 python3.6-dev python3-pip python3.6-venv
RUN apt-get install -y git

# update pip
RUN python3.6 -m pip install pip --upgrade
RUN python3.6 -m pip install wheel


ENV directory /home/ubuntu/docker_images/sage-demo

WORKDIR ${directory}

ADD requirement.txt ${directory}/requirement.txt

ADD testmodel.pkl ${directory}/testmodel.pkl

ADD predictor.py ${directory}/predictor.py

ADD start.sh ${directory}/start.sh

RUN pip3.6 install -r requirement.txt

ENTRYPOINT ["python3.6", "predictor.py"]
#CMD ["/bin/sh", "start.sh"]
#ENTRYPOINT ["/bin/sh", "start.sh"]
